### ISSUE TITLE
early return result decorator/operator

### ISSUE THREAD

**Issue by tl-flavio-barinas** [rustedpy/result#113]
What do you think about adding a decorator to bubble up an error result
```python

@result_ext
def foo() -> Result[T,E]:
  # would raise an `Exception` that would be captured by `result_ext` 
  a = bar().unwrap_or_return()
  
  # use the `__ipow__`(**=) operator as a short cut
  b **= bar()
  
  # or use the `__invert__`(~) operator
  c = ~bar()
  ~bar() 

  return Ok(T(...))
```

The most challenging part will be ensuring that the type hints of wrapped functions are correct so that mypy/pyright are able to analyze correctly. Optionally/alternatively we could raise a `ValueError` if the types don't match
```python
@result_ext(raise_value_error=true)
def foo() -> Result[_,E0]:
  # `a` should have a type hint a `T` if ok
  # if error the linter should capture that `E0` and `E1` don't match and optionally raise a `ValueError`
  a = ~bar()
  

@result_ext
def bar() -> Result[T,E1]:
  ...
```

**Comment by wbolster** [comment]
just thinking along, not endorsing this idea (yet 🙃)

or unary `+`: _positive vibes_ only:

```
x = +f()  # same as f().unwrap()
```

not sure if i like syntax magic though.

i don't see how this would need a decorator though?

**Comment by tl-flavio-barinas** [comment]
Not sure how I feel about the `__pos__` operator 😬.
 
 You need the decorator to capture an Exception and cause an early return rather than letting the exception surface to a try catch stmt.
 
 Here is an quick impl of the decorator:
 ```python
 def result_ext(func: Callable[P, Result[T, E]]) -> Callable[P, Result[T, E]]:
    @functools.wraps(func)
    def wrapper(*args: P.args, **kwargs: P.kwargs) -> Result[T, E]:
        try:
            return func(*args, **kwargs)
        except EarlyReturnException as e:
            return e.result
    return wrapper
```

So instead of having checks to see if the result has an error in every function you can bubble up the result 
```python

def foo_v0() -> Result[T,E]:
  a = bar()
  if a.is_err():
    return a.map_err(...)
  
  a = a.unwrap()

@result_ext
def foo_v1() -> Result[T,E]:
  a = ~bar().map_err(...)
```

**Comment by JLessinger** [comment]
This is similar to repeated `and_then()` operations or `do` notation, right? PR150 adds anonymous do 
expressions using `for ... in ...` generators. In a previous implementation, I had something like this proposal with `yield` standing in for Haskell's`<-`:

```
        @do
        def _result_sum(is_success1: bool, is_success2: bool) -> DoResult[int, str]:
            r1, r2 = _get_result(is_success1, 1), _get_result(is_success2, 2)
            x1 = yield r1
            x2 = yield r2
            return Ok(x1 + x2)
```

FWIW, the problem here was that the entire function gets wrapped into a generator which constrains the static type of the T values getting passed around. So `x1` and `x2` had to have the same type. 


But anyway, now you can do:

```
def foo_v2() -> Result[T,E]:
    a = bar().map_err(...)
    return do(
        ...
        for a_ok in a
    )        
```

**Comment by dogweather** [comment]
> This is similar to repeated `and_then()` operations or `do` notation, right? PR150 adds anonymous do expressions using `for ... in ...` generators…But anyway, now you can do…

I can't really connect the dots. How would we translate this Rust code? 

From #125 by @aukeschaap

```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}
```

The magic is really Rust's `?` language feature. But if a `do`, `and_then()` or `for` could approximate it expressively, that'd be nice.

**Comment by dogweather** [comment]
Just brainstorming. Here's a context manager version:

```python
def read_username_from_file() -> Result[T,E]:
    with rewrapping do:
        username_file = open("hello.txt").unwrap()
        username = ""
        username_file.read_to_string(username).unwrap()
        Ok(username)
```

**Comment by JLessinger** [comment]
I think something like this works? 

```
def read_username_from_file() -> Result[T, E]:
    username = ""
    return do(
        Ok(username)
        for username_file_ok in open("hello.txt")
        for _ in username_file.read_to_string(username)
    )
```

This should definitely work:


```
def read_username_from_file() -> Result[T, E]:
    username = ""
    return do(
        read_file_contents_as_string(file_ok)
        for file_ok in open("hello.txt")
    )
```

**Comment by dogweather** [comment]
> I think something like this works?

Thanks. That helps make it concrete. The reversed execution order would take some getting used to.

**Comment by dogweather** [comment]
Ah hah - thanks!

**Comment by francium** [comment]
We didn't really get anywhere with the original proposal of a early return operator. And given Python's restrictions, we can't really implement a proper `?` return operator, at least not without syntax magic involving operator overloading.

I'm going to close this for now and we can revisit it if there's interest again in the future.
