### ISSUE TITLE
Fix `sys.version_info` import

### ISSUE THREAD

**Issue by Tomperez98** [rustedpy/result#117]
https://github.com/microsoft/pylance-release/issues/4243#issuecomment-1509364152

Replace 

```python
if sys.version_info[:2] >= (3, 10):
    from typing import Final, Literal, ParamSpec, TypeAlias
else:
    from typing_extensions import Final, Literal, ParamSpec, TypeAlias
```

for the standard way (and the pattern that is supported in PEP 484 by static type checkers)

```python
if sys.version_info >= (3, 10):
    from typing import Final, Literal, ParamSpec, TypeAlias
else:
    from typing import Final, Literal

    from typing_extensions import ParamSpec, TypeAlias

```

**Comment by francium** [comment]
Thanks for the PR @Tomperez98 

Can you confirm this fixes the issue you're having with VS Code
You can install the latest master, now the PR is merged using,
```
pip install git+https://github.com/rustedpy/result
```

If you're able to confirm I'll create a new release of this library and publish it to pypi

**Comment by Tomperez98** [comment]
Seems fine to me

![image](https://user-images.githubusercontent.com/72174660/234324228-86f18fdd-d578-45ab-8037-a1daaa272258.png)
