### ISSUE TITLE
Remove the argument-less __init__ of Ok

### ISSUE THREAD

**Issue by mmohaveri** [rustedpy/result#119]
Currently, the Ok type's `__init__` has been defined as:

```python
    @overload
    def __init__(self) -> None:
        ...  # pragma: no cover

    @overload
    def __init__(self, value: T) -> None:
        ...  # pragma: no cover

    def __init__(self, value: Any = True) -> None:
        self._value = value
```

This messes with static type checkers (I've tested with pyright) as the following code has an error, but the type checker does not report it:

```python
def bad_ok() -> Result[str | None, Exception]:
    return Ok()
```

This causes the type checker to think everything is Ok, but in fact the return value of the functions does not match the expected return value, i.e. if you try to check for error by following code, you're code won't work, but your type checker can't help you:

```
match bad_ok():
  case Err():
     print("error"):
  case Ok(v):
     if v is None:
        print("I'm none")
```

**Comment by francium** [comment]
Opened https://github.com/rustedpy/result/pull/122 to address this

**Comment by francium** [comment]
I've made a preview release with this included, if everything looks okay, it will be made into 0.11.0 in the near future
https://pypi.org/project/result/0.11.0rc1/
