### ISSUE TITLE
Feature: Error propagation

### ISSUE THREAD

**Issue by aukeschaap** [rustedpy/result#125]
One of the reasons I use the `Result` type, is to gracefully handle errors, i.e. without raising exceptions. This leads me to often write code in the following pattern:

```
response = api.get(
    url=ENDPOINT,
    token=token,
)
if isinstance(response, Err):
    return response

actual_needed_value = response.value
```

Rust offers an operator to simplify this, the `?` operator. I was wondering why something so essential is not present in this library.

### Context
<details>
<summary>Two snippets containing example Rust code.</summary>
As context, this is how the `?` operator would simplify Rust code. This snippet

```
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let username_file_result = File::open("hello.txt");

    let mut username_file = match username_file_result {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut username = String::new();

    match username_file.read_to_string(&mut username) {
        Ok(_) => Ok(username),
        Err(e) => Err(e),
    }
}
```

can be written as

```
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}
```

</details>

**Comment by aukeschaap** [comment]
I just realized that it is not possible; How would you write a function that either evaluates to a value, or returns a value to the caller.

**Comment by francium** [comment]
The `?` operator is a language-level feature in Rust, we can't mimic that easily.

See the discussion here https://github.com/rustedpy/result/issues/113

**Comment by dogweather** [comment]
I **think** your example can be cleaned up with `match`. But still, we'll have this for every invocation that returns a `Result`.

```python
response = api.get(
    url=ENDPOINT,
    token=token,
)
if isinstance(response, Err):
    return response

actual_needed_value = response.value
```

becomes this (untested):

```python
match api.get(url=ENDPOINT, token=token):
    case Ok(v):  actual_needed_value = v
    case Err(e): return Err(e)
```
