### ISSUE TITLE
Remove `tests/test_pattern_matching.py` from mypy.exclude config

### ISSUE THREAD

**Issue by ThirVondukr** [rustedpy/result#134]
Linked issue: https://github.com/python/mypy/issues/10201
As of now that issue is closed and mypy supports pattern matching

**Comment by francium** [comment]
Perhaps I'm not fully understanding, can you clarify what you mean here? Or a PR would be great as well.

Right now we do run `tests/test_pattern_matching.py`, but only for python versions 3.10 and above.

**Comment by ThirVondukr** [comment]
Hm, sorry, I didn't consider pre 3.10 versions of python, would mypy flat out fail if you try to lint this file on 3.8 or 3.9? Because comment in `pyproject.toml` simply says that mypy doesn't support pattern matching, but it's no longer true

**Comment by francium** [comment]
Yeah because of differences between versions in what they support the GitHub CI config runs things based on what version. pattern matching, type checking, flake8, mypy are all configured like this.

**Comment by francium** [comment]
> Because comment in pyproject.toml simply says that mypy doesn't support pattern matching, but it's no longer true

```
# Exclude files with pattern matching syntax until Mypy supports it;
# see https://github.com/python/mypy/issues/10201
exclude = "tests/test_pattern_matching.py"
```

You're right. I'm not sure if there's a way to make it work between different versions though.
Perhaps that most logical thing to do here is wait until Python 3.8 and 3.9 become end-of-lie, then remove this exclude.

For now I think updating the comment to mention this would be best.

Anyway, I don't think this exclude is having any affect on users of this library, it only affects any developer working on this specific test file.

I'm going to push up a commit to update the comment on `pyproject.toml` and close this PR

**Comment by francium** [comment]
Comment updated in https://github.com/rustedpy/result/commit/cfda8ec7fb759c85d82b1d95afc1f7b7b0d91c19.

Trying to run mypy with a Python version that doesn't support pattern
matching results in the following error:

```
mypy tests/test_pattern_matching.py
tests/test_pattern_matching.py:11:12: error: invalid syntax; you likely need to run mypy using Python 3.11 or newer  [syntax]
```

**Comment by ThirVondukr** [comment]
I think comment in pyproject.toml was a bit misleading then 😅 maybe it should be changed to something like
```
Exclude files with pattern matching for testing on python versions older than 3.10
```
