### ISSUE TITLE
is there any plan to support port Option to this library?

### ISSUE THREAD

**Issue by Yansongsongsong** [rustedpy/result#136]

**Comment by francium** [comment]
There was previous interest for an Option in https://github.com/rustedpy/result/issues/43

I think it's worth considering. I'll wait to see if anyone else expresses interest or has any further ideas of suggestions

**Comment by francium** [comment]
We can keep this open

**Comment by francium** [comment]
I've reached out to the creator of https://pypi.org/project/maybe/, to see if we could possibly use that package name since that package is now unmaintained (since 2016)

Currently waiting to hear back.

**Comment by francium** [comment]
I haven't heard anything from the creator of https://pypi.org/project/maybe/. I'll try reaching out one more time.

There's also https://pypi.org/project/optional/, I'll reach out to the owner of that as well to see if they reply.

We might need to consider using a different name

Some ideas
- `maybe-py`
- `mightbe`
- `rustedpy-maybe` -- we could also start publishing `rustedpy-result`

**Comment by francium** [comment]
@Yansongsongsong would you like to test out the new package here https://github.com/rustedpy/maybe
If you notice any issues, bugs or have any suggestions you can open an issue on that repo.
