### ISSUE TITLE
mypy complains on "Missing return statement"

### ISSUE THREAD

**Issue by Corwinpro** [rustedpy/result#137]
Is this a known issue? What is the suggested way around this?

```python
from result import Result, Err, Ok


def foo() -> Result[int, int]:
    return Ok(1)


def bar() -> str:
    match foo():
        case Ok(value):
            return f"{value}"
        case Err(e):
            raise RuntimeError(e)
```

Running `mypy` on this results in

```
example.py:8: error: Missing return statement  [return]
```

**Comment by wbolster** [comment]
this is called an ‘exhaustiveness check’ and it can be achieved with mypy but requires more code than your example. a web search yields various articles about the details.

also read up on typing.Never in the stdlib which has an example but a rather limited explanation: https://docs.python.org/3/library/typing.html#typing.Never

**Comment by Corwinpro** [comment]
@wbolster Interestingly, this passes?..

```python
from result import Result, Err, Ok


def foo() -> Result[int, int]:
    return Ok(1)


def bar() -> str:
    result = foo()
    match result:
        case Ok(value):
            return f"{value}"
        case Err(e):
            raise RuntimeError(e)
```

**Comment by wbolster** [comment]
interesting, maybe mypy inference limitation? can you try `reveal_type()`?

**Comment by Corwinpro** [comment]
But this is not `result`-specific, I can see the same behaviour for any `Union` types

**Comment by francium** [comment]
This works,
```python
    match x := foo():
        case int(x): return x
        case str(x): raise ValueError(x)
```

**Comment by Corwinpro** [comment]
This is actually a mypy bug: https://github.com/python/mypy/issues/12998
