### ISSUE TITLE
Projects using `result`

### ISSUE THREAD

**Issue by fenilgmehta** [rustedpy/result#138]
Hello Everyone, thanks a lot for this wonderful library.

I would like to use this library, and it would be really helpful to understand how it is being used in other projects. If you are aware of any project which is using this, then please share it.

I feel we can also use the responses to add `Who's using Result?` section to the README.md file just like Ruff (https://github.com/astral-sh/ruff#whos-using-ruff)

**Comment by tobbber** [comment]
FYI: You can search github for `language:Python "from result import" OR "^import result"` and get some decent results

**Comment by francium** [comment]
Going to close this issue, but keeping it pinned for visibility 

**Please feel free to continue commenting here**
