### ISSUE TITLE
Misleading documentation regarding `res = Ok()`

### ISSUE THREAD

**Issue by lhpaoletti** [rustedpy/result#141]
When I try to use the statement `res = Ok()` I get a `TypeError`, which says

> Ok.__init__() missing 1 required positional argument: 'value'

This is contradictory to the library's documentation, which shows the following example:

```
>>> res1 = Ok()
>>> res1.value
True
```

I'm totally fine with writing `res = Ok(True)`, because the same statement in Rust would have been `let res = Ok(())` anyways and not `let res = Ok()`, because `Result<T, E>` is generic over some `T`. This wouldn't even compile, since there's no type to infer the type of `res` from and there's no type we could annotate `res` with...

# Proposal

The solution I'd propose to this issue is to remove the misleading example from the API documentation and to add the following example to it:

> When the type of the `Ok` value is irrelevant, we suggest using `Ok(True)` as in the Rust language we'd use `Ok(())`.
```
>>> res1 = Ok(True)
>>> res1.is_ok()
True
```

**Comment by francium** [comment]
Yes, it's possible the documentation has gone out of date with the actually API due to some recent changes.
`Ok` now requires a value.

Would you like to submit a PR request to fix this issue in the documentation?

**Comment by dolfinus** [comment]
Why such a simple fix of Readme requires a PR?

**Comment by wbolster** [comment]
because this is a volunteer-run project and nobody owes you anything

entitled behaviour will get you nowhere in open-source projects

there's literally an edit button on the page you complain about, ffs

**Comment by wbolster** [comment]
and of course, instead of replying to you, i could've done it myself

this proves exactly my point: you're just wasting others' energy with snarky remarks such as yours

**Comment by francium** [comment]
Asking for PR was also my way of inviting new contributors.
