### ISSUE TITLE
TypeGuards for fall-through (else) case without PEP 724 requirement.

### ISSUE THREAD

**Issue by minmax** [rustedpy/result#145]
Hi, i want to reopen discussion about type guards implemented with `__bool__` method, its already proposed in https://github.com/rustedpy/result/issues/69#issuecomment-1501206886

If `__bool__` method will be implemented, fall-through (else) case would work now, without required [PEP 724](https://peps.python.org/pep-0724/) implementation.

PR for issue: https://github.com/rustedpy/result/pull/144

thx @erictraut for very detailed explanation about TypeGuards implementation, i just copy&paste it here:
https://github.com/microsoft/pyright/issues/6140

Refer to [PEP 647](https://peps.python.org/pep-0647/#typeguard-type) for details about TypeGuard. User-defined type guards do not narrow types in the negative (else) case.

You may also be interested in [PEP 724](https://peps.python.org/pep-0724/), which is still in the draft stage. Pyright has provisional support for PEP 724 (you need to set the enableExperimentalFeatures setting to true), but I don't recommend doing this for production code at this time because the PEP could change or be rejected.

**Comment by rupurt** [comment]
Is this so you can do `go` like error handling? e.g.

```python
# ...
if is_err(res):
  raise "some error"
print("result was ok")
```

Currently I'm getting type errors that I can't use `ok` values in that form. I can only do `if/else` which creates a bunch of nesting e.g.

```python
if is_ok(res):
  print("result was ok")
else:
  raise "some error"
```

**Comment by francium** [comment]
Regarding `__bool__`, I'm going to have to say no at this time. This is not something I see that will be worth implementing right now.

While I can agree it does have some appeal, the ability to just do `if some_result: ...`, plus the benefit of better type checking until PEP 724, the biggest concern I have is it makes the code harder to read: am I looking at a boolean or a custom class instance that overrides `__bool__`?

I recall coming across some discussion on reddit about this library where one comment suggested usage of result in their code make it harder for unfamiliar developers to understand the code. Overriding `__bool__` would further lead to more confusion in more places -- especially given how often a `if some_result` is likely to be used.

I'll quote the second line of [The Zen of Python] as a closing thought,

> Explicit is better than implicit.

**Comment by francium** [comment]
@rupurt you can use `isinstance`, which works in that case,

```python
    x = something(2)
    if isinstance(x, Err):
        return
    x # x: Ok[int]
```

**Comment by rupurt** [comment]
Sweet. Works like a charm. Thanks @francium
