### ISSUE TITLE
[Redo  #108] Support do notation

### ISSUE THREAD

**Issue by JLessinger** [rustedpy/result#149]
Opening this because I didn't see a way to reopen 108 or a link to any associated PR. #150 is a proposal using `yield` to simulate <- notation as in Rust (or Haskell).

**Comment by JLessinger** [comment]
cc @francium

**Comment by francium** [comment]
#112 was the previous attempt

**Comment by JLessinger** [comment]
@francium , #150 is ready for review, thanks.

**Comment by francium** [comment]
@JLessinger had a suggestion for a decorator/yield based do-notation, but there were some complications involving type checking. In #150, the previous generator expression based do-notation, introduced in #112, was implemented.

I'm going to close this issue for now and in future, if necessary this or another new issue can be reopened as interest in this returns
