### ISSUE TITLE
Mapping exceptions to errors for as_result / as_result_async decorators

### ISSUE THREAD

**Issue by vkurilin** [rustedpy/result#156]
Hi!
I would like to know your thoughts on the idea: In decorators `as_result`/`as_result_async` the ability to set the mapping to an error type. 

Common boilerplate: 
```python
try:
    some_third_party_staff(...)
except ThirdPartyError:
    raise MyError

# or, if u trying to wrap it
try:
    some_third_party_staff(...)
except ThirdPartyError:
    return Err(MyError)
```

It seems like decorators could save some code:
```python
@as_result({ValueError: MyError})
def f() -> int:
    raise ValueError  # becomes Err

res = f()  # Err[MyError()]
```

I'll be happy to do a PR if it seems like a good idea to you

**Comment by wbolster** [comment]
i suspect type checkers won't be able to express/infer the types correctly. and type safety is a major goal of this project.

**Comment by wbolster** [comment]
in addition, wrapping/reraising errors is more involved than your example suggests.

the .wrap() function from the ‘exceptional’ package does this, including mappings with correct inheritance checks, exception causes, preservation or augmentation of error messages, etc:

https://exceptional.readthedocs.io/en/latest/

**Comment by vkurilin** [comment]
> in addition, wrapping/reraising errors is more involved than your example suggests.

Yes, I realize that exception handling is not the most trivial domain. 
And I like the idea of making it a separate package (I hope you won't mind contributions there 😉)

But at the same time, I believe it would be great to include an example in the documentation of the `result` itself, possibly as an optional dependency on `exceptional` and just an example of use.

Unlike Rust, in the Python world it is common to use exceptions, and there is a "gap" between the "ordinary" world and the `result` world, and I would like to provide the developer with convenient tools to smooth this gap out of the box

**Comment by francium** [comment]
This conversation has stalled. I'm going to close this for now. If interest picks up, please feel free to re-open.
