### ISSUE TITLE
Rewrite README in markdown

### ISSUE THREAD

**Issue by francium** [rustedpy/result#161]
The README was originally written in reStructuredText (RST) a long time ago -- perhaps before PyPI supported Markdown.
But [PyPI should now be able to render markdown][1].

Too often I've noticed myself and others making mistakes as RST is less common than Markdown.

**Great issue for any new contributor looking to help out.**

[1]: https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/#creating-a-readme-file

**Comment by dogweather** [comment]
Hey, I like it. I'll start it. 

I happened to just create a small PR for the current README. #163
