### ISSUE TITLE
Proposal to rename main branch from `master` to `main`

### ISSUE THREAD

**Issue by francium** [rustedpy/result#166]
Just wanted to post this to provide a heads up. I'm thinking of renaming the main branch from `master` to `main` for a couple of reasons, without introducing politics:

- GitHub has changed the default branch from `master` to `main`
- I've been using `main` for other projects, so less friction when I'm working on this repo

I'd like to hear from any **regular contributors** in case they would like to hold off on this switch -- perhaps they still use a `master` branch in other projects and this would introduce friction for them.

To be clear the friction would be quite minimal, it's just limited to typing `git checkout main` vs `git checkout master` etc. So it shouldn't be a big thing overall.

**Comment by wbolster** [comment]
yep, just do it!

**Comment by francium** [comment]
`main` is now the main branch of this project.
