### ISSUE TITLE
Optional callable args for `and_then`

### ISSUE THREAD

**Issue by rcaught** [rustedpy/result#172]
Using the Do notation, I can have a series of functions called that do not accept arguments, and only return `Result[None, str]`. That's works great!

```python
result: Result[None, str] = do(
    Ok(None)
    for a in my_object.prepare()
    for b in my_object.run()
    for c in my_object.cleanup()
)
```

If I want to use the `and_then` helper though, [the `op` `Result` is always passed to the `Callable`](https://github.com/rustedpy/result/blob/8f09f1e8b35bd81385f1009710cff2eb2d1f3ce2/src/result/result.py#L174).

For `and_then` to work for this case, I need to define a `none: None = None` parameter on every receiver.

Should it be possible to use `and_then` calls without passing an argument?

In Rust, it would look like:
```rust
let result = perform_action_one()
        .and_then(|_| perform_action_two())
        .and_then(|_| perform_action_three());
```

**Comment by francium** [comment]
Haven't touched rust in a while, so someone can correct me if I'm mistaken here:

In that rust example you've given, the anonymous function passed to `and_then` is discarding (technically ignoring) the passed in value.

The direct translation into Python would look like,
```python
result: Result[T, E] = (perform_action_one()  # replace T and E with actual types
    .and_then(lambda _: perform_action_two())
    .and_then(lambda _: perform_action_three())
```

> Should it be possible to use and_then calls without passing an argument?

Could it be possible, yes. Should it? Not as it's currently defined. This matches the Rust API, which also gets the value, as well as Haskell' 'bind' operator (`>>=`). Hopefully I haven't confused myself and stated something incorrect, especially in regards to Haskell.

With do-notation you can however do something like this,
```python
result = do(
    Ok(a)
    for a in run_a()
    for _ in run_b()
    for _ in run_c()
)
```

Which I believe matches the semantics of something like this in Haskell
```haskell
do
   line <- run_a
   run_b
   run_c
```

**Comment by rcaught** [comment]
> In that rust example you've given, the anonymous function passed to `and_then` is discarding (technically ignoring) the passed in value.

Correct AFAIK

> 
> The direct translation into Python would look like,
> 
> ```python
> result: Result[T, E] = (perform_action_one()  # replace T and E with actual types
>     .and_then(lambda _: perform_action_two())
>     .and_then(lambda _: perform_action_three())
> )
> ```

Yep, this is what I would like to have available.

> With do-notation you can however do something like this,
> 
> ```python
> result = do(
>     Ok(a)
>     for a in run_a()
>     for _ in run_b()
>     for _ in run_c()
> )
> ```

Yep, I can use this, I just find the `and_then` syntax clearer.
