### ISSUE TITLE
Document `if isinstance(x, Err)` pattern

### ISSUE THREAD

**Issue by francium** [rustedpy/result#174]
See https://github.com/rustedpy/result/issues/145#issuecomment-1879507088

This should be mentioned somewhere in the documentation until potential [PEP 724](https://peps.python.org/pep-0724/) improvements.

**Comment by Jylpah** [comment]
Is the lack of PEP 724 the reason why `mypy` does not accept `is_ok()` or `is_err()` results as guarantee for the result type? 

<img width="629" alt="image" src="https://github.com/rustedpy/result/assets/43722525/08790b6e-00f1-4647-8196-d08b67a3013a">

**Comment by francium** [comment]
> PS. Isn't this mentioned in the Summary in the second code block?

I think it may be inferred from that code example, but I opened this issue to make it explicitly documented. Someone a few weeks ago ran into a situation where they didn't realize that's how to use the isinstance to get proper type checking.

> Is the lack of PEP 724 the reason why mypy does not accept is_ok() or is_err() results as guarantee for the result type?

I believe so.

From PEP 724
> This PEP refines the TypeGuard mechanism introduced in [PEP 647](https://peps.python.org/pep-0647/). It allows type checkers to narrow types when a user-defined type guard function returns False. It also allows type checkers to apply additional (more precise) type narrowing under certain circumstances when the type guard function returns True.
