### ISSUE TITLE
Is there a clean way to handle error propagation?

### ISSUE THREAD

**Issue by AntonEriksson978** [rustedpy/result#178]
Looking at the example below, I feel like this can be written in a more concise way, especially the "case err return same err" part:

```python
result = some_function_returning_result()
match result:
  case Ok(value):
    # do something
    return Ok(some_new_value)
  case Err(error):
    return Err(error)
```

Thank you for your great work on this lib!

**Comment by francium** [comment]
I think you're talking about a early return mechanism like Rust and Zig have. See https://github.com/rustedpy/result/issues/113 discussion. But there's no native way to do this in Python without introducing hidden magic which may make the code harder to understand (for some at least).

**Comment by francium** [comment]
Going to close this for now, as I think it's a duplicate of #113. Please comment over there or reopen this discussion if this is not a duplicate.

**Comment by francium** [comment]
One more thing, which may help you out. Try the `and_then` operator or the  do-notation support. Both are mentioned in the README.md. Hope that helps.
