### ISSUE TITLE
Feature request: make `Err` "Falsy" by default

### ISSUE THREAD

**Issue by ericpan64** [rustedpy/result#186]
I'm writing a library that is relying on "truthy" and "falsy" assumptions. It'd be convenient if `Err` was falsy, or `Ok`/`Err` took the truthy/falsy of the embedded values. I think this would involve updating the `__bool__` operator in each class

Current behavior:
```python
from result import Ok, Err

if Ok(1):
  print("Hi") # prints!

if Err(1):
  print("Hi") # prints -- would prefer if this didn't print, though might make sense bc of enclosed value

if Err(False):
  print("Hi") # prints -- I don't think this should print

```

Desired behavior would be both `Err` cases above don't print

Let me know -- happy to take this on if it's a go. Thanks!

**Comment by francium** [comment]
It's unlikely this proposal will be accepted. It can be brought up before, See https://github.com/rustedpy/result/issues?q=__bool__

The result type is a different entity from a boolean. Trying to treat a result as a bool-ish value may be too implicit and magical, and additionally would lead to more complexity/cognitive overhead for those who come onto a result type for the first time and aren't familiar with it's semantics (which is likely the vast majority of python users)

The existing supported err/ok check should be used instead to maintain readability and explicitness.

Sorry, I can understand you may not agree with the approach. But it's unlikely this will be an acceptable change at this time. You're happy to try and change my mind with further arguments in favor of overloading the __bool__ here

**Comment by ericpan64** [comment]
That makes sense! Thanks for your work on this 💯
