### ISSUE TITLE
`TypeGuard` vs `TypeIs`

### ISSUE THREAD

**Issue by kreathon** [rustedpy/result#193]
> There is a proposed [PEP 724 – Stricter Type Guards](https://peps.python.org/pep-0724/) which may allow the is_ok and is_err type guards to work as expected in future versions of Python.

The linked PEP was withdrawn, however the same functionality was accepted as [`TypeIs`](https://peps.python.org/pep-0742/).

It can be used starting from Python3.13, but there is also already a backport in [`typing_extensions`](https://typing-extensions.readthedocs.io/en/latest/#typing_extensions.TypeIs). It is also already supported by type checkers like `mypy`.

I see two options for the project here:

1. start using from Python3.13 on (as soon as (if ?) it is supported by `result`)
2. already start using the backport for older Python versions

I would be happy to contribute (1. or 2).

**Comment by wbolster** [comment]
both sound good!
