### ISSUE TITLE
consider adding dunder-bool

### ISSUE THREAD

**Issue by wbolster** [rustedpy/result#61]
would you consider adding a `__bool__` magic method? see https://docs.python.org/3/reference/datamodel.html#object.__bool__

it would mean that `if result` and `if not result` would do the obvious thing.

note that type checkers like mypy will not infer types based on the result. unfortunately, it seems the newly added `typing.TypeGuard` functionality only applies to regular functions, not to methods.

**Comment by francium** [comment]
Hmm, not sure if I'd understand what someone was intending if I read `if result`. I think your #69 `is_ok`, `is_err` provider a much nicer approach no?

**Comment by wbolster** [comment]
yep, it seems this can never be made to work in a type-safe manner.

`typing.TypeGuard` does allow methods to be used as type guards, but only if they take one arg _after_ the implicit `self`:

> If a type guard function is implemented as an instance method or class method, the first positional argument maps to the second parameter (after "self" or "cls").
> – [PEP 647](https://www.python.org/dev/peps/pep-0647/)

and on top of that `def __bool__(self)` would be a ‘magic’ method that is not called directly.

while i think code like this reads elegantly:

``` python
res = do_something(...)
if res:
    do_something_with(res.value)
```

... type checkers would disagree, and that makes it not a good fit for this library.

**Comment by francium** [comment]
Does the walrus operator make sense (`:=`)? I've never used it but I came across this Rust syntax,
```
if let Ok(lines) = lines_from_file(filename) { ... }
```

**Comment by wbolster** [comment]
it would become

```python
if res := do_something(...):
    do_something_with(res.value)
```

this would shave off one line of code, and a unnecessary repetition of the variable name, but it suffers from the same problem: type checkers will _not_ be able to narrow type inside the `if` block to only `Ok`, which brings us back to the problem described in [my previous comment](https://github.com/rustedpy/result/issues/61#issuecomment-956479406)
