### ISSUE TITLE
use PEP 563 style annotations

### ISSUE THREAD

**Issue by wbolster** [rustedpy/result#70]
we should probably start using PEP563 (https://www.python.org/dev/peps/pep-0563/)

```python
from __future__ import annotations
```

... which means stringified type annotations are no longer needed.

this [requires python 3.7+](https://www.python.org/dev/peps/pep-0563/#enabling-the-future-behavior-in-python-3-7) though, so this would depend on

- [x] #49

**Comment by francium** [comment]
Yeah, let's wait for 3.6 to end of life and we can look at this.
