### ISSUE TITLE
Discussion: Forming a Chat Community

### ISSUE THREAD

**Issue by rvente** [rustedpy/result#85]
Hey maintainers, thank you for your great work on this project. This library has brought me great joy and it feels like the missing pieces of python are being filled in.

Are there ongoing thoughts about forming a "rustedpy" community? The repo seems to be growing and a community chat could be an opportunity for growth and cross-pollination of ideas. Expanding into online communities would allow us to mockup, mature our ideas, and implement them. 

In particular, I was wondering if there is active interest in bringing [Map](https://doc.rust-lang.org/std/iter/struct.Map.html) and [filter](https://doc.rust-lang.org/std/iter/struct.Filter.html) to rustedpy.

 Gitter or Discord seem like the github community's go-to options for this purpose. Thanks for your time.

**Comment by wbolster** [comment]
i have experimentally opened the github "discussions" feature for this repository.

(personally i am not interested in using yet another chat/communication medium for a small project like this)

**Comment by rvente** [comment]
Thank you very much. That's perfect. My point has been addressed. Closing.
