### ISSUE TITLE
any appetite for `.unwrap()` that prints the err value?

### ISSUE THREAD

**Issue by noxasaxon** [rustedpy/result#98]
Occasionally I have critical errors that cannot be remediated so i'd like to .unwrap(), but I have already captured valuable information in the Result's Error type that get ignored in the UnwrapError.

 Rather than checking for an error, then raising a new error with the captured message I created a `.unwrap_print()` function (not a great name) to relay this information:
 
```python
from result import Result, Ok, Err, UnwrapError
from typing import NoReturn

 def unwrap_print(self) -> NoReturn:
    """
    Raises an `UnwrapError` but prints the error value.
    """
    raise UnwrapError(
        self,
        f"Called `Result.unwrap()` on an `Err` value:: {self.value.__repr__()}",
    )

Err.unwrap_print = unwrap_print  # type: ignore
```

```sh
>>> f.unwrap_print()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in unwrap_print
result.result.UnwrapError: Called `Result.unwrap()` on an `Err` value:: ValueError('testing')
```

Is this something that we can either add to the existing `.unwrap()` method or possibly add as a new method? I'm willing to make the PR but just wanted to see if there were any design constraints you've already considered first.

**Comment by noxasaxon** [comment]
it looks like the same behavior happens with `.expect("msg")` as well

**Comment by francium** [comment]
Hi @noxasaxon 

I just tried it out with Rust and it always includes the value in the panic that's triggered.

For example,
```
fn main() {
    let x: Result<i32, i32> = Err(33);
    x.unwrap(); // output 1
    x.expect("some message"); // output 2
}
```

Output 1
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 33', src/main.rs:3:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Output 2
```
thread 'main' panicked at 'some message: 33', src/main.rs:3:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

---

So based on this, how about we modify the exception we raise on `expect` and `unwrap` to include the inner value of the Err? Similarly for `expect_err` and `unwrap_err`?

**Comment by wbolster** [comment]
i agree with @francium. adding more unnecessary api just adds confusion.

if the `Err` value is an exception instance (`BaseException` really), the raised error could even set that as its _cause_, essentially becoming `raise UnwrapError(...) from exc`. this means the python interpreter will even prints its backtrace if it bubbles up uncaught!

**Comment by francium** [comment]
@noxasaxon if you're happy with our suggestions, we can make this change. You're welcome to make a PR if you'd like to contribute.

**Comment by noxasaxon** [comment]
yeah i can make a PR later today!

**Comment by guacs** [comment]
Is this something that's still being planned? The PR #100 seems to have become stale though it would be a great addition imo.

**Comment by francium** [comment]
@guacs Sorry I've been busy with a few things. I've still got this listed as a todo, I'll try to get to this as soon as I can.

**Comment by guacs** [comment]
> @guacs Sorry I've been busy with a few things. I've still got this listed as a todo, I haven't forgotten, I'll try to get to this as soon as I can.

No worries, and thank you for this great library :)
